schema_version = "1.0.0"
id = "wiggle_2"
version = "2.2.5"
name = "Wiggle 2"
tagline = "Simulate spring-like physics on Bone transforms"
maintainer = "Steve Miller <https://github.com/shteeve3d/blender-wiggle-2>"
type = "add-on"
blender_version_min = "3.0.0"
license = ["SPDX:GPL-3.0-or-later"]
category = "animation"
